const products = [
  { id: 0, category: 'Pozole', name: 'Pozole Grande', price: 95 },
  { id: 1, category: 'Pozole', name: 'Pozole Grande Solo Maiz', price: 75 },
  { id: 2, category: 'Pozole', name: 'Pozole Chico', price: 85 },
  { id: 3, category: 'Pozole', name: 'Pozole Chico Solo Maiz', price: 65 },
  { id: 4, category: 'Sopas', name: 'Sopa de Tortilla', price: 60 },
  { id: 5, category: 'Sopas', name: 'Consome Ranchero', price: 45 },
  { id: 6, category: 'Sopas', name: 'Caldo de Pollo', price: 45 },
  { id: 7, category: 'Sopas', name: 'Arroz blanco', price: 35 },
  { id: 8, category: 'Gorditas', name: 'Gordita de Chicharron', price: 40 },
  { id: 9, category: 'Gorditas', name: 'Gordita de Requeson', price: 40 },
  { id: 10, category: 'Gorditas', name: 'Gordita Combinada', price: 45 },
  { id: 11, category: 'Gorditas', name: 'Gordita con quesillo', price: 15 },
  { id: 12, category: 'Tostadas', name: 'Tostada de Pata', price: 40 },
  { id: 13, category: 'Tostadas', name: 'Tostada de Tinga de Res', price: 40 },
  { id: 14, category: 'Tostadas', name: 'Tostada de Tinga de Pollo', price: 40 },
  { id: 15, category: 'Tostadas', name: 'Tostada de Picadillo', price: 40 },
  { id: 16, category: 'Flautas', name: 'Flautas Tradicionales', price: 70 },
  { id: 17, category: 'Flautas', name: 'Flautas Ahogadas en Salsa Verde', price: 80 },
  { id: 19, category: 'Enchiladas o Chilaquiles', name: 'Enchiladas o Chilaquiles de Pollo', price: 75 },
  { id: 20, category: 'Enchiladas o Chilaquiles', name: 'Enchiladas o Chilaquiles de cerdo', price: 75 },
  { id: 21, category: 'Enchiladas o Chilaquiles', name: 'Enchiladas o Chilaquiles de Constilla de res', price: 110 },
  { id: 22, category: 'Enchiladas o Chilaquiles', name: 'Enchiladas o Chilaquiles Gratinados', price: 20 },
  { id: 23, category: 'Sopes', name: 'Sope Sencillo', price: 32 },
  { id: 24, category: 'Sopes', name: 'Sope Con Guisado', price: 45 },
  { id: 25, category: 'Sopes', name: 'Sope con Bistec', price: 53 },
  { id: 26, category: 'Sopes', name: 'Sope con Quesillo', price: 15 },
  { id: 27, category: 'Quesadillas', name: 'Quesadilla Sencilla', price: 32 },
  { id: 28, category: 'Quesadillas', name: 'Quesadilla con Guisado', price: 36 },
  { id: 29, category: 'Quesadillas', name: 'Quesadilla con Bistec con queso', price: 45 },
  { id: 30, category: 'Quesadillas', name: 'Quesadilla Preparada', price: 5 },
  { id: 31, category: 'Pambazos', name: 'Pambazo Tradicional', price: 45 },
  { id: 32, category: 'Pambazos', name: 'Pambazo Con Guisado', price: 50 },
  { id: 33, category: 'Pambazos', name: 'Pambazo con Quesillo', price: 15 },
  { id: 34, category: 'Tacos', name: 'Taco de Bistec', price: 25 },
  { id: 35, category: 'Tacos', name: 'Taco de Pollo', price: 25 },
  { id: 36, category: 'Tacos', name: 'Taco de Chuleta', price: 25 },
  { id: 37, category: 'Tacos', name: 'Taco de Longaniza', price: 25 },
  { id: 38, category: 'Tacos', name: 'Taco de Campechano', price: 25 },
  { id: 39, category: 'Tacos', name: 'Taco con queso', price: 10 },
  { id: 34, category: 'Tacos', name: 'Orden de Bistec', price: 65 },
  { id: 41, category: 'Tacos', name: 'Orden de Pollo', price: 65 },
  { id: 42, category: 'Tacos', name: 'Orden de Chuleta', price: 65 },
  { id: 43, category: 'Tacos', name: 'Orden de Longaniza', price: 65 },
  { id: 44, category: 'Tacos', name: 'Orden de Campechano', price: 65 },
  { id: 45, category: 'Tacos', name: 'Orden con queso', price: 15 },
  { id: 46, category: 'Gringas', name: 'Gringa de Bistec', price: 85 },  
  { id: 47, category: 'Gringas', name: 'Gringa de Pollo', price: 85 },
  { id: 48, category: 'Gringas', name: 'Gringa de Chuleta', price: 85 },
  { id: 49, category: 'Gringas', name: 'Gringa de Longaniza', price: 85 },
  { id: 50, category: 'Gringas', name: 'Gringa de Campechano', price: 90 },
  { id: 51, category: 'Quesos Fundidos', name: 'Sencillo', price: 55 },
  { id: 52, category: 'Quesos Fundidos', name: 'Con Bistec', price: 70 },
  { id: 53, category: 'Quesos Fundidos', name: 'Con Pollo', price: 70 },
  { id: 54, category: 'Quesos Fundidos', name: 'Con Chuleta', price: 70 },
  { id: 55, category: 'Quesos Fundidos', name: 'Con Longaniza', price: 70 },
  { id: 56, category: 'Quesos Fundidos', name: 'Campechano', price: 75 },
  { id: 57, category: 'Trompos', name: 'Trompo de Bistec', price: 169 },
  { id: 58, category: 'Trompos', name: 'Trompo de Pollo', price: 169 },
  { id: 59, category: 'Trompos', name: 'Trompo de Chuleta', price: 169 },
  { id: 60, category: 'Trompos', name: 'Trompo de Longaniza', price: 169 },
  { id: 61, category: 'Trompos', name: 'Trompo Campechano', price: 179 },
  { id: 62, category: 'Trompos', name: 'Trompo Azteca', price: 30 },
  { id: 63, category: 'Especiales', name: 'Milanesa de Pollo', price: 110 },
  { id: 64, category: 'Especiales', name: 'Pechuga de pollo asada', price: 110 },
  { id: 65, category: 'Especiales', name: 'Costilla o Carne asada de res', price: 110 },
  { id: 66, category: 'Especiales', name: 'Costilla Nortena', price: 120 },
  { id: 67, category: 'Especiales', name: 'Ensalada Suprema', price: 110 },
  { id: 68, category: 'Bebidas', name: 'Agua de Jamaica', price: 35 },
  { id: 69, category: 'Bebidas', name: 'Agua de Jamaica sin Azucar', price: 35 },
  { id: 70, category: 'Bebidas', name: 'Agua de Horchata', price: 35 },
  { id: 71, category: 'Bebidas', name: 'Coca Cola', price: 35 },
  { id: 72, category: 'Bebidas', name: 'Coca Cola sin Azucar', price: 35 },
  { id: 73, category: 'Bebidas', name: 'Sidral Mundet', price: 35 },
  { id: 74, category: 'Postres', name: 'Flan de Cajeta', price: 35 },
  { id: 75, category: 'Postres', name: 'Flan Napolitano', price: 35 },
  { id: 76, category: 'Postres', name: 'Fresas con Crema', price: 35 },
  { id: 77, category: 'Postres', name: 'Arroz con Leche', price: 35 },
  { id: 78, category: 'Extras y Complementos', name: 'Orden de carne de pozole', price: 38 },
  { id: 79, category: 'Extras y Complementos', name: 'Orden de Chicharron', price: 25 },
  { id: 80, category: 'Extras y Complementos', name: 'Orden de Aguacate', price: 35 },
  { id: 81, category: 'Extras y Complementos', name: 'Orden de Crema', price: 15 },
  { id: 82, category: 'Extras y Complementos', name: 'Orden de Queso Rallado', price: 15 },
  { id: 83, category: 'Extras y Complementos', name: 'Tostadas Extras (3 pzas)', price: 10 }
];

const categories = [
  { id: 0, description: 'Delicioso pozole rojo estilo jalisco, acompanado de tres tostadas de maiz crujientes. Nuestra recomendacion es agregarle salsa para pozole hecha a base de chiles de arbol.', name: 'Pozole', image: '/products/pozole.jpg' },
  { id: 1, description: '', name: 'Sopas', image: '/products/sopas.jpg' },
  { id: 2, description: '', name: 'Gorditas', image: '/products/gorditas.jpg' },
  { id: 3, description: '', name: 'Tostadas', image: '/products/tostadas.jpg' },
  { id: 4, description: '', name: 'Flautas', image: '/products/flautas.jpg' },
  { id: 5, description: '', name: 'Enchiladas o Chilaquiles', image: '/products/enchiladas.jpg' },
  { id: 6, description: '', name: 'Sopes', image: '/products/sopes.jpg' },
  { id: 7, description: '', name: 'Quesadillas', image: '/products/quesadillas.jpg' },
  { id: 8, description: '', name: 'Pambazos', image: '/products/pambazos.jpg' },
  { id: 9, description: '', name: 'Tacos', image: '/products/tacos.jpg' },
  { id: 10, description: '', name: 'Gringas', image: '/products/gringas.jpg' },
  { id: 11, description: '', name: 'Quesos Fundidos', image: '/products/queso.jpg' },
  { id: 12, description: '', name: 'Trompos', image: '/products/trompo.jpg' },
  { id: 13, description: '', name: 'Especiales', image: '/products/milanesa.jpg' },
  { id: 14, description: '', name: 'Bebidas', image: '/products/horchatas.jpg' },
  { id: 15, description: '', name: 'Postres', image: '/products/flan.jpg' },
  { id: 16, description: '', name: 'Extras y Complementos', image: '' }
];

export function getCategories() {
  return categories;
}

export function getProducts() {
  return products;
}